export { Switch, Composite, Click_Anywhere, Click_Mask } from './basic'
export { Image, GIF, Video } from './media'
export { Sidescroll } from './scroll'
export { Drag_to_Target } from './dnd'
export { Complete_Maze } from './maze'
